name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build, tag and push image to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t maximb805/store:$IMAGE_TAG .
          docker push maximb805/store:$IMAGE_TAG
          echo "::set-output name=image::maximb805/store:$IMAGE_TAG"

      # - name: other step that needs the created image   
      #   run: |
      #     ${{ steps.build-image.outputs.image }}  так можно использовать output
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1 # для яндекса есть спец. action
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # это секреты в github
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # можно глянуть более удачный регион

      - name: Set kubectl context to AWS 
        run: aws eks update-kubeconfig --name aws-cluster-name --region us-east-1 # естественно нужны данные реального AWS кластера

      - name : Deploy Image to Amazon EKS
        run: |
          kubectl set image deployment/store store=${{ steps.build-image.outputs.image }}

